EPSILON: 0.1
REGULARIZATION: 0.0001
LEARNING_RATE: 0.01
INPUT_DIMENSION: (32, 3, 12)
MOMENTUM: 0.9
OUTPUT_DIMENSION: 32
HIDDEN_LAYERS: [
    {"filters": 75, "kernel_size": (4, 4)},
    {"filters": 75, "kernel_size": (4, 4)},
    {"filters": 75, "kernel_size": (4, 4)},
    {"filters": 75, "kernel_size": (4, 4)},
    {"filters": 75, "kernel_size": (4, 4)},
    {"filters": 75, "kernel_size": (4, 4)},
]
