"GAMES_FILE": '/home/heiko/Projects/heiko/skat-zero/test.gz'
"CPUCT": 1
"MC_SIMULATIONS": 100
"EPSILON": 0.1
"ALPHA": 0.8
"ACTION_SIZE": 32
"REGULARIZATION": 0.0001
"LEARNING_RATE": 0.01
"MOMENTUM": 0.9
"MEMORY_SIZE": 30
"TRAINING_LOOPS": 1
"BATCH_SIZE": 50
"EPOCHS": 10
